lane :adhoc do |options|
  # 如果你用 pod install
  cocoapods
  # 不带adhoc参数，sigh会自动生成App Store证书(公司或个人帐户)
  sigh(adhoc: true)
  # 指定输出目录
  gym(
    configuration:options[:config],
    scheme:options[:scheme],
    output_directory: options[:outpath],
    output_name: options[:ipaname],
    export_method:'ad-hoc',
    clean:true
    )
end

lane :appstore do |options|
  # 如果你用 pod install
  cocoapods
  # 不带adhoc参数，sigh会自动生成App Store证书(公司或个人帐户)
  sigh
  # 指定输出目录
  gym(
    configuration:options[:config],
    scheme:options[:scheme],
    output_directory: options[:outpath],
    output_name: options[:ipaname],
    export_method:'app-store',
    clean:true
  )
  deliver(
    force: true,
    skip_screenshots:true,
    skip_metadata: true
  )
end


