lane :adhoc do |options|
  # 如果你用 pod install
  cocoapods
  # 不带adhoc参数，sigh会自动生成App Store证书(公司或个人帐户)
  # sigh(adhoc: true)
  # 指定输出目录
  ipa(
    configuration:options[:config],
    scheme:options[:scheme],
    destination: options[:outpath],
    clean:true
    )
end
