lane :adhoc do |options|
  # 如果你用 pod install
  cocoapods
  # 不带adhoc参数，sigh会自动生成App Store证书(公司或个人帐户)
  sigh(adhoc: true)
  # 指定输出目录
  gym(
    configuration:options[:config],
    scheme:options[:scheme],
    output_directory: options[:outpath],
    export_method:'ad-hoc',
    clean:true
    )
  pgyer(api_key: "1c85c26364b99fd4c0c9534504af1e71", user_key: "4d3a4ece05e37ffda29bb8f4d5b506f2")
end

lane :appstore do |options|
  # 如果你用 pod install
  cocoapods
  # 不带adhoc参数，sigh会自动生成App Store证书(公司或个人帐户)
  sigh
  # 指定输出目录
  gym(
    configuration:options[:config],
    scheme:options[:scheme],
    output_directory: ‘./build’,
    export_method:'app-store',
    clean:true
  )
  deliver(
    force: true,
    skip_screenshots:true,
    skip_metadata: true
  )
end


